some more refinement, refs #1322

diff --git a/lspiceiso b/lspiceiso
--- a/lspiceiso
+++ b/lspiceiso
@@ -12,7 +12,7 @@ usage()
 cat << EOF
 usage: $0 options
 
-This script run the test1 or test2 over a machine.
+#ToDo Write some useful description
 
 OPTIONS:
    -h      Show this message
@@ -25,66 +25,95 @@ EOF
 }
 
 
-if [ -f ./liso.conf ]; then  
+if [ -f ./liso.conf ]; then
     . ./liso.conf
 elif [ -f ./etc/liso.conf ]; then
     . /etc/liso.conf
 else
-    IsoBasePath=/srv/iso
-    PublishingBase=/srv/iso-publisher
+    Webuser=webdevel
+    Webhost=test.siduction.org
+    IsoPath=/srv/iso
+    PublishingPath=/srv/iso-publisher
+    ServerPath=/var/www/virtual/webdevelopment/iso/siduction
+
+    # hold the three newes builds, delete older ones
+    DeleteOldPublishedIsos=4
+
+    CurrentReleaseName=firestarter
+    NextReleaseName=paintitblack
+    XperimenatalReleaseName=thunderstruck
+
     IsoFlavour=nox
     IsoArch=amd64
     SpicePort=6666
-    IsoRelease=paintitblack
+    ReleaseCode=next
     SMP=2
 fi
 
-while getopts “f:a:p:r:s:” OPTION; do
-     case $OPTION in
+while getopts “f:a:p:r:s:h” OPTION; do
+     case ${OPTION} in
          f)
-             IsoFlavour=$OPTARG
+             IsoFlavour=${OPTARG}
              ;;
          a)
-             IsoArch=$OPTARG
+             IsoArch=${OPTARG}
              ;;
          p)
-             OptSpicePort=$OPTARG
+             OptSpicePort=${OPTARG}
              ;;
          r)
-             IsoRelease=$OPTARG
+             ReleaseCode=${OPTARG}
              ;;
          s)
-             SMP=$OPTARG
+             SMP=${OPTARG}
              ;;
-         ?,h)
+         h)
              usage
              exit
              ;;
      esac
 done
 
-if [ -z $IsoFlavour ] || [ -z $IsoArch ]; then
+case ${ReleaseCode} in
+    current)
+        IsoRelease=${CurrentReleaseName}
+        ;;
+    next)
+        IsoRelease=${NextReleaseName}
+        ;;
+    xperimental)
+        IsoRelease=${XperimenatalReleaseName}
+        ;;
+    *)
+        echo "ReleaseCode nicht bekannt ${ReleaseCode}"
+        exit 1
+        ;;
+esac
+
+if [ -z ${IsoFlavour} ] || [ -z ${IsoArch} ]; then
      usage
      exit 1
 fi
 
-SearchIso="/srv/iso/${IsoFlavour}/${IsoArch}/*${IsoRelease}*iso"
-IsoFile=$(ls $SearchIso | tail -n1)
+SearchIso="${IsoPath}/${IsoFlavour}/${IsoArch}/*${IsoRelease}*iso"
+IsoFile=$(ls ${SearchIso} | tail -n1)
 
-if [ x$IsoFile == 'x' ]; then
+if [ "x${IsoFile}" == "x" ]; then
     echo ""
     echo "================================================"
-    echo "Isofile with Searchpattern $SearchIso not found!"
+    echo "Isofile with Searchpattern ${SearchIso} not found!"
     echo "eventually you would like one of these images:  "
     echo ""
-    ls /srv/iso/${IsoFlavour}/${IsoArch}/*iso
+    ls ${IsoPath}/${IsoFlavour}/${IsoArch}/*iso
     echo ""
-    exit 1
+    echo "Quitting now"
+    exit 0
 fi
 
-IsoVersion=$(echo $IsoFile | awk -F '-' '{ print  $2 }')  # 13.1.1
-IsoRelease=$(echo $IsoFile | awk -F '-' '{ print  $3 }')  # paintitblack
-IsoDateTime=$(echo ${IsoFile%.*} | awk -F '-' '{ print  $(NF) }' | sed "s/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3_\4-/1" ) # datetime
+IsoName=$(basename ${IsoFile%.*})
+IsoVersion=$(echo ${IsoName} | awk -F '-' '{ print  $2 }')  # 13.1.1
+IsoRelease=$(echo ${IsoName} | awk -F '-' '{ print  $3 }')  # paintitblack
+IsoDateTime=$(echo ${IsoName} | awk -F '-' '{ print  $(NF) }' | sed "s/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3_\4-/1" ) # datetime
 
 case ${IsoFlavour} in
     cinnamon)
@@ -129,7 +158,7 @@ echo "Iso-Flavour:  ${IsoFlavour}"
 echo "Architecture: ${IsoArch}"
 echo "Release:      ${IsoRelease}"
 echo "SMP:          ${SMP}"
-echo "Iso-Date/Time $IsoDateTime"
+echo "Date/Time:    ${IsoDateTime}"
 echo "Spice-Port:   ${SpicePort}"
 echo ""
 echo ""
@@ -153,8 +182,8 @@ qemu-system-x86_64 \
         -chardev spicevmc,id=spicechannel0,name=vdagent \
 
 # Nach Beenden der KVM, Interface stoppen und entfernen
-#sudo /sbin/ifconfig $INTERFACE down
-#sudo /usr/sbin/tunctl -d $INTERFACE &> /dev/null
+#sudo /sbin/ifconfig ${INTERFACE} down
+#sudo /usr/sbin/tunctl -d ${INTERFACE} &> /dev/null
 #reset
 
 
