new kvmiso, former lspiceiso added two wrappers around kvmiso, lspiceiso and lspiceuefi fixed architecture to all, it's simple shell scripting

diff --git a/server/bin/kvmiso b/server/bin/kvmiso
--- a/server/bin/kvmiso
+++ b/server/bin/kvmiso
@@ -20,6 +20,7 @@ OPTIONS:
   -a      ISO architecture, should be 'i386' or 'amd64'
   -f      'cinnamon','gnome','lxde','lxqt','kde','mate','nox','xfce','xorg'
   -k      Keyboard
+  -r      release: '', 'current','next','xperimental'
   -s      smp - 1..8 (default: 2)
   -u      UEFI-Boot
   -v      VGA-Option ('qxl', 'std', 'cirrus' Standard: qxl)
@@ -41,17 +42,23 @@ BIOSDISPLAY='BIOS'
 
 while getopts “a:f:i:k:p:r:s:t:hu” OPTION; do
     case ${OPTION} in
-         a)
-            Arch=${OPTARG}
+        a)
+            IsoArch=${OPTARG}
             ;;
         f)
-            Flavour=${OPTARG}
+            IsoFlavour=${OPTARG}
+            ;;
+        i)
+            IsoFile=$(realpath ${OPTARG})
             ;;
         k)
             Keyoard=${OPTARG}
             ;;
         p)
             OptSpicePort=${OPTARG}
+            ;;
+        r)
+            ReleaseCode=${OPTARG}
             ;;
         s)
             SMP=${OPTARG}
@@ -71,7 +78,50 @@ while getopts “a:f:i:k:p:r:s:t:hu” OPTION; do
     esac
 done
 
-case ${Flavour} in
+case ${ReleaseCode} in
+    current)
+        IsoRelease=${CurrentReleaseName}
+        ;;
+    next)
+        IsoRelease=${NextReleaseName}
+        ;;
+    xperimental)
+        IsoRelease=${XperimentalReleaseName}
+        ;;
+    *)
+        echo "ReleaseCode nicht bekannt ${ReleaseCode}"
+        ;;
+esac
+
+if [ -z ${IsoFlavour} ] || [ -z ${IsoArch} ]; then
+     usage
+     exit 1
+fi
+
+if [ "x${IsoFile}" == "x" ]; then
+   SearchIso="${IsoPath}/${IsoFlavour}/${IsoArch}/*${IsoRelease}*iso"
+   IsoFile=$(ls --sort=time ${SearchIso} | head -n1)
+fi
+
+if [ "x${IsoFile}" == "x" ]; then
+    echo ""
+    echo "================================================"
+    echo "Isofile with Searchpattern ${SearchIso} not found!"
+    echo "eventually you would like one of these images:  "
+    echo ""
+    ls ${IsoPath}/${IsoFlavour}/${IsoArch}/*iso
+    echo ""
+    echo "Quitting now"
+    exit 0
+fi
+
+IsoName=$(basename ${IsoFile%.*})
+IsoVersion=$(echo ${IsoName}  | awk -F '-' '{ print  $2 }')  # 13.1.1
+IsoRelease=$(echo ${IsoName}  | awk -F '-' '{ print  $3 }')  # paintitblack
+IsoFlavour=$(echo ${IsoName}  | awk -F '-' '{ print  $4 }')  # nox
+IsoDateTime=$(echo ${IsoName} | awk -F '-' '{ print  $(NF) }' | sed "s/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3_\4-/1" ) # datetime
+
+case ${IsoFlavour} in
     cinnamon)
         SpicePort=7210
         ;;
@@ -104,7 +154,7 @@ case ${Flavour} in
         ;;
 esac
 
-case ${Arch} in
+case ${IsoArch} in
     amd64)
         SpicePort=${SpicePort}
         ;;
@@ -112,26 +162,44 @@ case ${Arch} in
         SpicePort=$(expr ${SpicePort} + 1000)
         ;;
 esac
+
+case ${ReleaseCode} in
+    current)
+        SpicePort=${SpicePort}
+        ;;
+    next)
+        SpicePort=$(expr ${SpicePort} + 100)
+        ;;
+    xperimental)
+        SpicePort=$(expr ${SpicePort} + 200)
+        ;;
+esac
+
+
 ## OptSpicePort ToDo ##
 ## spice-vdagebt ToDo ##
 
 echo ""
 echo ""
 echo "=============================="
-echo "=     KVM   Spice  ${BIOSDISPLAY}     ="
+echo "=     KVM   Spice   ${BIOSDISPLAY}     ="
 echo "=============================="
-echo "Flavour:      ${Flavour}"
-echo "Architecture: ${Arch}"
+echo "Iso-Version:  ${IsoVersion}"
+echo "Iso-Flavour:  ${IsoFlavour}"
+echo "Architecture: ${IsoArch}"
+echo "Release:      ${IsoRelease}"
+echo "Iso-File:     ${IsoFile}"
 echo "SMP:          ${SMP}"
+echo "Date/Time:    ${IsoDateTime}"
 echo "Spice-Port:   ${SpicePort}"
 echo ""
 echo ""
 
 
 qemu-system-x86_64 \
-    -name siduction-${Flavour} \
-    -drive if=virtio,file=${QcowPath}/${Flavour}-${Arch}.qcow2,media=disk,cache=unsafe \
-    -boot order=c \
+    -name siduction-${IsoFlavour} \
+    -drive if=virtio,file=${QcowPath}/${IsoFlavour}-${IsoArch}.qcow2,media=disk,cache=unsafe \
+    -boot order=d \
     -enable-kvm \
     -m 4096 \
     ${UEFIBIOS} \
@@ -142,6 +210,8 @@ qemu-system-x86_64 \
     -net nic,model=virtio \
     -net user \
     -smp ${SMP} \
+    -cdrom ${IsoFile} \
     -device virtio-serial-pci \
     -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
     -chardev spicevmc,id=spicechannel0,name=vdagent \
+
